version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: emp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mindz@123
      MYSQL_DATABASE: emp_onboarding
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: emp_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Mindz@123
      DB_NAME: emp_onboarding

volumes:
  - mysql_data:
